"""
core/job_role_database.py
──────────────────────────
Single source of job-role profiles for the AI Resume Analyzer.

This module now relies **exclusively** on real profiles loaded from
data/real_job_profiles.json (generated by scripts/build_real_job_profiles.py).

No synthetic fallback is provided. If a profile is missing, a ValueError is raised.
"""

import json
from pathlib import Path
from typing import Any, Dict, List

# ─────────────────────────────────────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────────────────────────────────────

JOB_LEVELS: List[str] = ["Entry", "Mid", "Senior"]

EXPERIENCE_RANGE: Dict[str, Dict] = {
    "Entry":  {"min": 0,  "max": 2,  "label": "0–2 years"},
    "Mid":    {"min": 2,  "max": 5,  "label": "2–5 years"},
    "Senior": {"min": 5,  "max": 20, "label": "5+ years"},
}

# ─────────────────────────────────────────────────────────────────────────────
# STATIC METADATA
# Keys are "Role_Level" strings, identical to real_job_profiles.json keys.
# Contains fields that cannot be derived from job-ad text alone.
# Add entries here whenever a new role is added.
# ─────────────────────────────────────────────────────────────────────────────

_STATIC_METADATA: Dict[str, Dict[str, Any]] = {

    # ── Software Engineer ─────────────────────────────────────────────────────
    "Software Engineer_Entry": {
        "role_description":   "Entry-level software engineering positions",
        "min_experience_years": 0,
        "required_education": "Bachelors",
    },
    "Software Engineer_Mid": {
        "role_description":   "Mid-level software engineering positions",
        "min_experience_years": 2,
        "required_education": "Bachelors",
    },
    "Software Engineer_Senior": {
        "role_description":   "Senior software engineering positions",
        "min_experience_years": 5,
        "required_education": "Bachelors",
    },

    # ── Web Developer ─────────────────────────────────────────────────────────
    "Web Developer_Entry": {
        "role_description":   "Entry-level web development positions",
        "min_experience_years": 0,
        "required_education": "Bachelors",
    },
    "Web Developer_Mid": {
        "role_description":   "Mid-level web development positions",
        "min_experience_years": 2,
        "required_education": "Bachelors",
    },
    "Web Developer_Senior": {
        "role_description":   "Senior web development positions",
        "min_experience_years": 5,
        "required_education": "Bachelors",
    },

    # ── Data Analyst ──────────────────────────────────────────────────────────
    "Data Analyst_Entry": {
        "role_description":   "Entry-level data analyst positions",
        "min_experience_years": 0,
        "required_education": "Bachelors",
    },
    "Data Analyst_Mid": {
        "role_description":   "Mid-level data analyst positions",
        "min_experience_years": 2,
        "required_education": "Bachelors",
    },
    "Data Analyst_Senior": {
        "role_description":   "Senior data analyst positions",
        "min_experience_years": 5,
        "required_education": "Bachelors",
    },

    # ── Data Scientist ────────────────────────────────────────────────────────
    "Data Scientist_Entry": {
        "role_description":   "Entry-level data science positions",
        "min_experience_years": 0,
        "required_education": "Bachelors",
    },
    "Data Scientist_Mid": {
        "role_description":   "Mid-level data science positions",
        "min_experience_years": 2,
        "required_education": "Bachelors",
    },
    "Data Scientist_Senior": {
        "role_description":   "Senior data science positions",
        "min_experience_years": 5,
        "required_education": "Masters",
    },

    # ── Cloud Developer ───────────────────────────────────────────────────────
    "Cloud Developer_Entry": {
        "role_description":   "Entry-level cloud development positions",
        "min_experience_years": 0,
        "required_education": "Bachelors",
    },
    "Cloud Developer_Mid": {
        "role_description":   "Mid-level cloud development positions",
        "min_experience_years": 2,
        "required_education": "Bachelors",
    },
    "Cloud Developer_Senior": {
        "role_description":   "Senior cloud development positions",
        "min_experience_years": 5,
        "required_education": "Bachelors",
    },

    # ── Machine Learning Engineer ─────────────────────────────────────────────
    "Machine Learning Engineer_Entry": {
        "role_description":   "Entry-level machine learning engineering positions",
        "min_experience_years": 0,
        "required_education": "Bachelors",
    },
    "Machine Learning Engineer_Mid": {
        "role_description":   "Mid-level machine learning engineering positions",
        "min_experience_years": 2,
        "required_education": "Bachelors",
    },
    "Machine Learning Engineer_Senior": {
        "role_description":   "Senior machine learning engineering positions",
        "min_experience_years": 5,
        "required_education": "Masters",
    },

    # ── DevOps Engineer ───────────────────────────────────────────────────────
    "DevOps Engineer_Entry": {
        "role_description":   "Entry-level DevOps engineering positions",
        "min_experience_years": 0,
        "required_education": "Bachelors",
    },
    "DevOps Engineer_Mid": {
        "role_description":   "Mid-level DevOps engineering positions",
        "min_experience_years": 2,
        "required_education": "Bachelors",
    },
    "DevOps Engineer_Senior": {
        "role_description":   "Senior DevOps engineering positions",
        "min_experience_years": 5,
        "required_education": "Bachelors",
    },
}


def _get_metadata(role: str, level: str) -> Dict[str, Any]:
    """Return static metadata for a (role, level) pair, or defaults if absent."""
    key = f"{role}_{level}"
    mins = {"Entry": 0, "Mid": 2, "Senior": 5}
    return _STATIC_METADATA.get(key, {
        "role_description":   f"{role} {level.lower()} role",
        "min_experience_years": mins.get(level, 0),
        "required_education": "Bachelors",
    })


# ─────────────────────────────────────────────────────────────────────────────
# REAL PROFILES — loaded once at import time
# ─────────────────────────────────────────────────────────────────────────────

def _load_real_profiles() -> Dict[str, Dict[str, Any]]:
    """
    Load data/real_job_profiles.json from the project root.
    Returns an empty dict if the file is absent or unreadable.
    """
    json_path = Path(__file__).resolve().parent.parent / "data" / "real_job_profiles.json"
    if not json_path.exists():
        return {}
    try:
        with open(json_path, encoding="utf-8") as f:
            return json.load(f)
    except Exception as exc:  # noqa: BLE001
        import warnings
        warnings.warn(
            f"job_role_database: could not load {json_path}: {exc}. "
            "No profiles available.",
            RuntimeWarning,
            stacklevel=2,
        )
        return {}


_REAL_PROFILES: Dict[str, Dict[str, Any]] = _load_real_profiles()


# ─────────────────────────────────────────────────────────────────────────────
# PUBLIC API (no fallback)
# ─────────────────────────────────────────────────────────────────────────────

def list_roles() -> List[str]:
    """
    Return a sorted list of unique role names from real profiles.
    Returns empty list if no profiles are loaded.
    """
    if not _REAL_PROFILES:
        return []
    roles = {v["role"] for v in _REAL_PROFILES.values() if "role" in v}
    return sorted(roles)


def get_job_role_profile(role: str, level: str) -> Dict[str, Any]:
    """
    Return the full profile dict for (role, level) **from real profiles only**.

    Raises:
        ValueError: if level is invalid, or if the profile does not exist in
                    real_job_profiles.json.
    """
    if level not in JOB_LEVELS:
        raise ValueError(
            f"Level '{level}' is invalid. Choose from: {JOB_LEVELS}"
        )

    key = f"{role}_{level}"
    if key not in _REAL_PROFILES:
        available = list_roles()
        raise ValueError(
            f"No real profile found for role='{role}', level='{level}'. "
            f"Available roles: {available}"
        )

    # Start with the real profile, then overlay static metadata
    profile = dict(_REAL_PROFILES[key])   # shallow copy
    meta = _get_metadata(role, level)

    # Ensure expected fields exist
    profile.setdefault("num_jds", 0)
    profile.setdefault("skill_frequencies", {})
    profile.setdefault("required_skills",  [])
    profile.setdefault("preferred_skills", [])
    profile.setdefault("job_document", "")

    # Overlay metadata (static fields always override JSON)
    profile.update(meta)
    profile["role"]  = role
    profile["level"] = level
    return profile


def get_job_description_text(role: str, level: str) -> str:
    """
    Return the job_document string for the given role and level.
    """
    return get_job_role_profile(role, level)["job_document"]